### ISSUE TITLE
fp_control is broken on spark 7111 and 7162 (segfaults, Inappropriate ioctl for device)

### ISSUE THREAD

**Issue by lprot** [Duckbox-Developers/driver#2]
```
/tmp/fp_control: SW Version 1.04
Model: spark
vBoxType: 11
Selected Model: Edision Spark frontpanel control utility
Config file (/etc/vdstandby.cfg) not found,
using standard config:Config:
Display:0, DISPLAYCUSTOM = 0, CUSTOM = Unknown, WAKEUPDECREMENT 300
root@spark:~#

root@spark:~# /tmp/fp_control -tm
/tmp/fp_control: SW Version 1.04
Model: spark
vBoxType: 11
Selected Model: Edision Spark frontpanel control utility
Config file (/etc/vdstandby.cfg) not found,
using standard config:Config:
Display:0, DISPLAYCUSTOM = 0, CUSTOM = Unknown, WAKEUPDECREMENT 300
Segmentation fault
root@spark:~#

root@spark:~# /tmp/fp_control -l 0 1
/tmp/fp_control: SW Version 1.04
Model: spark
vBoxType: 11
Selected Model: Edision Spark frontpanel control utility
Config file (/etc/vdstandby.cfg) not found,
using standard config:Config:
Display:0, DISPLAYCUSTOM = 0, CUSTOM = Unknown, WAKEUPDECREMENT 300
Setled: Inappropriate ioctl for device

```

**Comment by MastaG** [comment]
Hi lprot, did you ever found a fix this?

**Comment by lprot** [comment]
Hi, no never.

**Comment by BPanther** [comment]
Do you use all of the DDT or a "mix" with other driver (maybe other aotom) etc.?

**Comment by lprot** [comment]
If you use old aotom from taapat's images then it is working. So the regression happened in new aotoms.

**Comment by MastaG** [comment]
Yes, but afaik his aotom didn't drive the vfd of my spark7162.
Only duckbox's aotom_spark driver with skl's patch (in oe-alliance
meta-fulan layer) works for me.

But I could never get fp-control working without complaining about ioctls..

Op za 23 feb. 2019 07:53 schreef lprot <notifications@github.com>:

**Comment by BPanther** [comment]
I have not this receiver, but an other user has test this. -tm requires a parameter, without -> segfault. That's right but not really a problem.

An then the second problem with "Inappropriate ioctl for device".

spark7162:~# fp_control -l 0 1
fp_control: SW Version 1.04
Model: spark7162
vBoxType: 11
Selected Model: Edision Spark frontpanel control utility
configs: DISPLAY = 1, DISPLAYCUSTOM = 1, CUSTOM =  %H:%M:%S
, WAKEUPDECREMENT 300

spark7162:~# fp_control -l 1 1
fp_control: SW Version 1.04
Model: spark7162
vBoxType: 11
Selected Model: Edision Spark frontpanel control utility
configs: DISPLAY = 1, DISPLAYCUSTOM = 1, CUSTOM =  %H:%M:%S
, WAKEUPDECREMENT 300

No problem with the DDT GIT:

BTW: Where is the file /etc/vdstandby.cfg ? Maybe also a problem for unknown errors. Seems to be not the DDT GIT build.

**Comment by lprot** [comment]
Why to close it if it was not fixed?

**Comment by Frankenstone** [comment]
you must use with parameter
`fp_control -tm 0
fp_control: SW Version 1.04
Model: spark7162
vBoxType: 7
Selected Model: Edision Spark frontpanel control utility
configs: DISPLAY = 1, DISPLAYCUSTOM = 1, CUSTOM =     %H:%M:%S    
, WAKEUPDECREMENT 300
spark7162-1:~#
`

**Comment by Frankenstone** [comment]
You must use with Args 0 or 1
No Probelm with DDT Git

> fp_control -tm 0
fp_control: SW Version 1.04
Model: spark7162
vBoxType: 7
Selected Model: Edision Spark frontpanel control utility
configs: DISPLAY = 1, DISPLAYCUSTOM = 1, CUSTOM =     %H:%M:%S    
, WAKEUPDECREMENT 300
spark7162-1:~#

> fp_control -tm 1
fp_control: SW Version 1.04
Model: spark7162
vBoxType: 7
Selected Model: Edision Spark frontpanel control utility
configs: DISPLAY = 1, DISPLAYCUSTOM = 1, CUSTOM =     %H:%M:%S    
, WAKEUPDECREMENT 300
spark7162-1:~# 


> -tm  --time_mode         Args: 0/1
        toggle 12/24 hour mode

**Comment by BPanther** [comment]
There is no fix needed, because it works with DDT build. And as I sayd here: https://github.com/Duckbox-Developers/driver/issues/2#issuecomment-466674672 from Feb 23, 2019:
"Where is the file /etc/vdstandby.cfg ? Maybe also a problem for unknown errors. Seems to be not the DDT GIT build."
