### ISSUE TITLE
Spark7162 with OpenATV 6.4 can't tune or view DVB-T1 channels

### ISSUE THREAD

**Issue by mjfwalsh** [Duckbox-Developers/driver#3]
I'm not sure if this is the right place to post this but here goes.

I recently upgraded my SAB Unix Triple HD from OpenATV 6.0 to OpenATV 6.4, and promptly lost the ability to view terrestrial DVB-T channels.*

I tried various fixes including: restoring my bouquets from backups, using older and newer versions of terrestrial.xml, and using the TerrestrialScan plugin. But nothing worked.

What did work was copying the spark7162.ko module from OpenATV 6.0 to OpenATV 6.4.

So I figure there's a problem with this driver.

(* Irish digital terrestrial HD and SD channels, branded as "Saorview", broadcast over DVB-T1.)

**Comment by BPanther** [comment]
Please write this at OATV forum - here is only Neutrino, not E2.

**Comment by mjfwalsh** [comment]
I do understand that you're only interested in Neutrino, but if there's a problem with the driver on Enigma2 there's probably going to be a problem on Neutrino too.

I've tracked down the bug to [this diff](/oe-alliance/oe-alliance-core/commit/0b76eb6a99a5deefb9c48ba0f53496d92bd4e7ac#diff-a6284de865f3a6ee45c0a49996892e55909a71da235d5ef488153443108be4b0) which switched the e2 recipe which uses this repository from [e9402706](/Duckbox-Developers/driver/commit/e94027065dc756ea41f537d1d3d215a96d549b94) (7 November 2017) to [b269c18f](https://github.com/Duckbox-Developers/driver/commit/b269c18f195aa97cfdfa970480c43407f8ced533) (28 February 2018).

When I switched the recipe back to the older commit, my dvt-t1 service was restored.

**Comment by BPanther** [comment]
I have asked a user and T is working with neutrino and a 7162.

**Comment by mjfwalsh** [comment]
I'm afraid I've tried a recent neutrino image available from linuxsat-support.com but I wasn't able to tune in any terrestrial channels.

I have however managed to narrow down what appears to have caused the issue, and have made a pull request: #4
